/***************************************************************************************************************************
 * This portion of the code originates from the Beremiz project, which is licensed under the GNU General Public License 
 * Version 2 (GPLv2). It has been temporarily incorporated into our current project, which is under the Apache License 
 * Version 2.0. We are aware of the licensing incompatibility between GPLv2 and Apache License Version 2.0 and are 
 * actively working on developing a more suitable solution tailored to our specific needs. This integration is 
 * provisional, and our goal is to replace this temporary implementation with our own, fully compliant version as soon 
 * as possible. We acknowledge the contribution of the MatIEC project and intend to ensure all uses are in line with 
 * its licensing terms during this transitional period. All users of this code are advised to consider the licensing 
 * implications of the GPLv3 and Apache License Version 2.0.
 ****************************************************************************************************************************/

/*
 * Generated by erpcgen 1.12.0 on Fri Mar 22 05:00:10 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_PLCObject_client_hpp_)
#define _erpc_PLCObject_client_hpp_

#include "erpc_PLCObject_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class BeremizPLCObjectService_client: public BeremizPLCObjectService_interface
{
    public:
        BeremizPLCObjectService_client(erpc::ClientManager *manager);

        virtual ~BeremizPLCObjectService_client();

        virtual uint32_t AppendChunkToBlob(const binary_t * data, const binary_t * blobID, binary_t * newBlobID);

        virtual uint32_t GetLogMessage(uint8_t level, uint32_t msgID, log_message * message);

        virtual uint32_t GetPLCID(PSKID * plcID);

        virtual uint32_t GetPLCstatus(PLCstatus * status);

        virtual uint32_t GetTraceVariables(uint32_t debugToken, TraceVariables * traces);

        virtual uint32_t MatchMD5(const char * MD5, bool * match);

        virtual uint32_t NewPLC(const char * md5sum, const binary_t * plcObjectBlobID, const list_extra_file_1_t * extrafiles, bool * success);

        virtual uint32_t PurgeBlobs(void);

        virtual uint32_t RepairPLC(void);

        virtual uint32_t ResetLogCount(void);

        virtual uint32_t SeedBlob(const binary_t * seed, binary_t * blobID);

        virtual uint32_t SetTraceVariablesList(const list_trace_order_1_t * orders, uint32_t * debugtoken);

        virtual uint32_t StartPLC(void);

        virtual uint32_t StopPLC(bool * success);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpc_PLCObject_client_hpp_
